#!/usr/bin/env python3

import logging
import argparse
import pathlib
import os
import subprocess
import json
import pandas as pd
import re
import secrets

logger = logging.getLogger(__name__)




def generate_report(datas):
    
    datas = pd.concat(datas)
    
    print("number of domains tested :",datas['domain'].nunique())
    print("number of total row : ",datas.shape[0])
    print("binarys : ", datas['bin'].unique())

    ##### mean time
    print("\n########## mean time ##########")

    median_time = datas[['domain','median','bin']].pivot_table(index='domain',columns='bin',values='median')
    
    if datas['bin'].nunique() > 1:
        median_time['diff'] = median_time.apply(lambda row: row['zonemaster-cli'] - row['gonemaster'], axis=1)
        median_time['percent'] = median_time.apply(lambda row: 1-(row['gonemaster']/row['zonemaster-cli']), axis=1)

    resume_stats = pd.DataFrame({   'mean': median_time.mean(), 
                                    'median': median_time.median(),
                                    'p90': median_time.quantile(q=0.90),
                                    'p95': median_time.quantile(q=0.95)})

    print(resume_stats)

    if  datas['bin'].nunique() > 1:
        print("\n# domain with biggest diff\n")
        print(median_time.nlargest(10,'percent'))

    ##### mean user time
    print("\n########## user time ##########")

    user_time = datas[['domain','user','bin']].pivot_table(index='domain',columns='bin',values='user')
    resume_stats = pd.DataFrame({   'mean':  user_time .mean(), 
                                    'median': user_time .median(),
                                    'p90':  user_time .quantile(q=0.90),
                                    'p95':  user_time .quantile(q=0.95)})
    print(resume_stats)

    ##### mean system time
    print("\n########## system time ##########")

    user_time = datas[['domain','system','bin']].pivot_table(index='domain',columns='bin',values='system')
    resume_stats = pd.DataFrame({   'mean':  user_time .mean(), 
                                    'median': user_time .median(),
                                    'p90':  user_time .quantile(q=0.90),
                                    'p95':  user_time .quantile(q=0.95)})
    print(resume_stats)


if __name__ == '__main__':

    # setup cli parser 
    parser = argparse.ArgumentParser(
                    prog='benchmarking tools for zonemaster and gonemaster',
                    description='',
                    epilog='')
    parser.add_argument("--log-level", "-l", nargs='?',
                    default="WARNING",
                    choices=["CRITICAL","ERROR","WARNING","INFO","DEBUG"])


    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('domain', nargs='?') 
    group.add_argument('--batch', nargs='?', type=pathlib.Path)
    group.add_argument('--report', nargs='*', type=pathlib.Path)

    parser.add_argument('--cache', action='store_true')
    parser.add_argument('--cache_dir', type=pathlib.Path, default='/tmp')
    parser.add_argument('--runs', nargs='?', type=int, default=1)
    parser.add_argument('--output', type=pathlib.Path)
    parser.add_argument('--profile', type=pathlib.Path)
    parser.add_argument('--bin', nargs='?', default='zonemaster-cli')

    args = parser.parse_args()

    # setup logging
    logging.basicConfig()
    logger.setLevel(args.log_level)

    logger.debug(f"args: {args}")
    
    # generate report from files
    if args.report:
        datas=[]

        #load all the data!
        for dfile in args.report:
            logger.info("reading data file: %s"%dfile)
            datas.append(pd.read_json(dfile))
            logger.info("data shape : %s",datas[-1].shape)
        
        generate_report(datas)
        exit()

    domains_list = []
    if args.domain:
        domains_list.append(args.domain)
    else:
        domains_list = open(args.batch,'r').readlines()
        #remove \n to all domains
        domains_list = [domain.rstrip() for domain in domains_list]

    all_datas = []

    for domain in domains_list:

        # if we are using cache
        # check if cache exist
        cache_file = f"{args.cache_dir}/{domain}.cache"
        if args.cache:
            if  not (os.path.exists(cache_file)
                and os.access(cache_file, os.R_OK)
                and os.path.getsize(cache_file) > 0):

                print(f"{cache_file} file does not exist, creating it ...")
                cli_cmd = f"{args.bin} --save {cache_file} {domain}"
                subprocess.run(cli_cmd.split())

        if args.runs == 0:
            logger.debug(f"runs set to {args.runs}, skip test part for {domain}")
            continue
	

        # building command line
        cli_cmd = f"{args.bin}"

        if args.cache:
            cli_cmd += " --restore %s/%s.cache"%(args.cache_dir, domain)

        if args.profile:
            cli_cmd += f" --profile {args.profile}"
        
        cli_cmd += f" {domain}"
        logger.debug(f"cli_cmd: {cli_cmd}")


        # create temporary file
        hyper_output_file="/tmp/tmp%s-%s.hyper"%(secrets.token_hex(4),args.bin)

        #hyper_cmd=["hyperfine", "--prepare", cli_cmd , "--runs", str(args.runs), cli_cmd, "--export-json", hyper_output_file]
        hyper_cmd=["hyperfine", "--runs", str(args.runs), cli_cmd, "--export-json", hyper_output_file]
        logger.debug(f"hyper_cmd: {hyper_cmd}")
        subprocess.run(hyper_cmd)

        #read json file 
        with open(hyper_output_file, 'r') as file:
            data = json.load(file)
            data = data['results'][0]

            data['domain'] = domain
            data['bin'] = args.bin
            data['cache'] = args.cache
            data['profile'] = str(args.profile)

            all_datas.append(data)
        
        # delete temporary file
        os.remove(hyper_output_file)

    #### OUTPUT

    # no output if no test run
    if args.runs <= 0:
        exit()

    if args.output:
        with open(args.output,'w') as file:
            json.dump(all_datas, file)
        exit()
    else:
        generate_report([pd.DataFrame.from_dict(all_datas)])

