[env]
MISE_INSTALLS_DIR = "{{config_root}}/.mise/installs"
PERL_CPANM_OPT = "--notest --from https://cpan.metacpan.org/"

[tools]
go = "latest"
hyperfine = "latest"
perl = "latest"
python = "3.14"

[tasks.dep]
description = "install dependencies"
run = [	"pip install -r requirements.txt",
	"cpanm Statistics::Descriptive Text::SimpleTable::AutoWidth"
	]

[tasks.gonemaster]
description = "install gonemaster"
run = [	"go install codeberg.org/pawal/gonemaster/cmd/gonemaster@latest" ]
