#!/usr/bin/env python3

import logging
import argparse
import os
import subprocess
import json
import pandas as pd
import re

logger = logging.getLogger(__name__)

tests_list = ["ALL", "Address", "Basic", "Connectivity", "Consistency", "DNSSEC", "Delegation", "Nameserver", "Syntax", "Zone"]

def get_zonemaster_versions():
    l=subprocess.run(['zonemaster-cli','--version'], capture_output=True)
    lines = l.stdout.decode('utf-8').strip().split('\n')

    # Regex for catching name and version
    pattern = r'(.+?)\s+version\s+(.+)'

    result = {}
    for line in lines:
        if line.strip():  # Skip lignes vides
            match = re.match(pattern, line.strip())
            if match:
                name = match.group(1).strip()
                version = match.group(2).strip()
                result[name] = version

    return result

def create_directories():
    dirs = ['cache']
    dirs += ['output']
    dirs += ['hyperfine']

    logger.debug("list of directories to create: %s",dirs)

    for nd in dirs:
        # Create the directory
        try:
            os.makedirs(nd)
            logger.info(f"Nested directories '{nd}' created successfully.")
        except FileExistsError:
            logger.info(f"One or more directories in '{nd}' already exist.")
        except PermissionError:
            logger.error(f"Permission denied: Unable to create '{nd}'.")
            exit()
        except Exception as e:
            logger.error(f"An error occurred: {e}")
            exit()

# function called by the 'cache' sub command
def cli_action_cache(args):
    logger.debug(args)

    domains_list = open(args.domain,'r').readlines()
    #remove \n to all domains
    domains_list = [domain.rstrip() for domain in domains_list]

    logger.info("domains list loaded: %d domains", len(domains_list))

    for domain in domains_list:
        logger.debug("building cache for domain %s",domain)

        for test in args.test:
            logger.debug("building cache for domain %s for test %s",domain, test)

            if os.path.isfile(f"cache/{domain}_{test}.cache"):
                logger.debug("the %s file already exists, skipping", f"cache/{domain}_{test}.cache")
                continue
            if test!='ALL':
                cmd = ["zonemaster-cli",f"--save=cache/{domain}_{test}.cache",f"--test={test}",f"{domain}"]
            else:
                cmd = ["zonemaster-cli",f"--save=cache/{domain}_{test}.cache",f"{domain}"]

            logger.debug("subprocess: %s",cmd)
            subprocess.run(cmd, capture_output=False)
    return

# function called by the 'run' sub command
def cli_action_run(args):
    logger.debug(args)

    domains_list = open(args.domain,'r').readlines()
    #remove \n to all domains
    domains_list = [domain.rstrip() for domain in domains_list]

    logger.info("domains list loaded: %d domains", len(domains_list))

    zm_versions = get_zonemaster_versions()
    logger.info("zonemaster versions:")
    for k,v in zm_versions.items():
        logger.info("\t%s : %s",k,v)

    for domain in domains_list:
        for test in args.test:
            logger.info("run benchmark for %s test %s", domain, test)

            # Emit warning if cache file is not found
            if not os.path.isfile(f"cache/{domain}_{test}.cache"):
                logger.warning("cache for domain %s and test %s not found",domain, test)

            if test!='ALL':
                zm_cmd=f"zonemaster-cli --restore=cache/{domain}_{test}.cache --test={test} --json {domain} >> output/{domain}_{test}.out"
            else:
                zm_cmd=f"zonemaster-cli --restore=cache/{domain}_{test}.cache --json {domain} >> output/{domain}_{test}.out"

            hyper_output_file=f"hyperfine/{domain}_{test}.json"

            if os.path.isfile(hyper_output_file):
                logger.debug("the %s file already exists, skipping", hyper_output_file)
                continue
            else:
                cmd=["hyperfine", "--prepare", zm_cmd , "--runs", str(args.run), zm_cmd, "--export-json", hyper_output_file]

                logger.debug("subprocess: %s",cmd)
                subprocess.run(cmd)

            # Inject more data inside the hyperfine output file

            with open(hyper_output_file,'r') as file:
                data = json.loads(file.read())
                data['results'][0]['domain'] = domain
                data['results'][0]['test'] = test
                # copie versions data
                for k,v in zm_versions.items():
                    data['results'][0][k] = v

            with open(hyper_output_file,'w') as file:
                json.dump(data, file)


    return

# function called by the 'gather' sub command
def cli_action_gather(args):
    logger.debug(args)

    gathered_data = pd.DataFrame(columns=['command', 'mean', 'stddev', 'median', 'user', 'system', 'min', 'max', 'times', 'exit_codes', 'domain', 'test', 'Zonemaster-CLI', 'Zonemaster-Engine', 'Zonemaster-LDNS', 'NL NetLabs LDNS'])
    for file in os.listdir("hyperfine"):
        logger.debug("gather hyperfine result from file %s", file)

        with open(f"hyperfine/{file}",'r') as f:
            data = json.loads(f.read())
            result = data['results'][0]
            gathered_data.loc[len(gathered_data)] = result

    with open('dataframe.json', 'w') as json_file:
        json_string = gathered_data.to_json(orient='records', indent=4)
        json_file.write(json_string)

    return

if __name__ == '__main__':

    # setup cli parser 
    parser = argparse.ArgumentParser(
                    prog='zonemaster benchmarking tools',
                    description='',
                    epilog='')
    parser.add_argument("--log-level", "-l", nargs='?',
                    default="WARNING",
                    choices=["CRITICAL","ERROR","WARNING","INFO","DEBUG"])

    subparsers = parser.add_subparsers(required=True)

    # create the parser for the "cache" command
    parser_cache = subparsers.add_parser('cache', help="build cache")
    parser_cache.add_argument('--domain',nargs='?',required=True)
    parser_cache.add_argument('--test',nargs='*', choices=tests_list, default=tests_list)
    parser_cache.set_defaults(func=cli_action_cache)

    # create the parser for the "run" command
    parser_run = subparsers.add_parser('run', help="run benchmark")
    parser_run.add_argument('--domain',nargs='?',required=True)
    parser_run.add_argument('--test',nargs='*', choices=tests_list, default=tests_list)
    parser_run.add_argument('--run',nargs='?', default=3, type=int)
    parser_run.set_defaults(func=cli_action_run)

    # create the parser for the "gather" command
    parser_gather = subparsers.add_parser('gather', help='build dataframe.json')
    parser_gather.set_defaults(func=cli_action_gather)

    args = parser.parse_args()

    # setup logging
    logging.basicConfig()
    logger.setLevel(args.log_level)


    create_directories()

    # run cli_action
    args.func(args)
