#!/usr/bin/env python3

import logging
import argparse
logger = logging.getLogger(__name__)

def cli_action_cache(args):
    logger.debug(args)
    return

def cli_action_run(args):
    logger.debug(args)
    return

def cli_action_gather(args):
    logger.debug(args)
    return

if __name__ == '__main__':
    
    # setup cli parser 
    parser = argparse.ArgumentParser(
                    prog='zonemaster benchmarking tools',
                    description='',
                    epilog='')
    parser.add_argument("--log-level", "-l", nargs='?',
                    default="WARNING",
                    choices=["CRITICAL","ERROR","WARNING","INFO","DEBUG"])

    subparsers = parser.add_subparsers(required=True)

    # create the parser for the "cache" command
    parser_cache = subparsers.add_parser('cache', help="build cache")
    parser_cache.add_argument('--domain',nargs='?',required=True)
    parser_cache.set_defaults(func=cli_action_cache)

    # create the parser for the "run" command
    parser_run = subparsers.add_parser('run', help="run benchmark")
    parser_run.add_argument('--domain',nargs='?',required=True)
    parser_run.set_defaults(func=cli_action_run)

    # create the parser for the "gather" command
    parser_gather = subparsers.add_parser('gather', help='build dataframe.json')
    parser_gather.set_defaults(func=cli_action_gather)

    args = parser.parse_args()
   
    # setup logging
    logging.basicConfig()
    logger.setLevel(args.log_level)

    # run cli_action
    args.func(args)
